#
# Copyright (C) 2019-2020 Heaptrace Technology
#

-
  name: Playbook for services installations
  hosts: localhost
  tasks:

     ##Check JAVA version 
    - name: Fetch Java version
      shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
      register: java_version

     ##Check Git version 
    - name: Fetch NPM version
      shell: git --version | awk '{print $3}'
      register: git_version

     ##Check NPM version 
    - name: Fetch NPM version
      shell: 'npm --version'
      register: npm_version

     ## Check Angular Cli Version
    - name: Fetch Angular CLI version
      shell: ng version | grep Angular | head -n 1 | awk '{print $3}'
      register: angular_version

     ## Check Docker version
    - name: Fetch Docker version
      shell: docker --version | awk '{print $3}'| sed 's/.$//'
      register: docker_version

     ## Check Docker-compose version
    - name: Fetch Docker-compose version
      shell: docker-compose version | grep docker-compose | awk '{print $3}' | sed 's/.$//'
      register: docker_version

     ##Install Git if not present
    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes
      register: git_install

     ##Install Docker if not present
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      register: docker_install
    - debug: var=docker_install.stdout_lines

     ##Install Docker-Compose if not present
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

     ##Install NPM if not present 



     ##Install Angular CLI if not installed
    - name: Install Angular CLI
      shell: npm install -g @angular/cli

     ##Git clone of the project
    - name: Node-App = Git pull node app
      git:
       repo: 'https://github.com/darshan-ht/node-app.git'
       dest: ./code/node-app
       clone: yes
      become_user: root

    ##Git clone of the project
    - name: angular app = Git pull 
      git:
       repo: 'https://github.com/darshan-ht/angular-app.git'
       dest: ./code/angular-app
       clone: yes
      become_user: root

    ##Git clone of the project
    - name: Docker-compose = Git pull 
      git:
       repo: 'https://github.com/darshan-ht/compose.git'
       dest: ./code/compose
       clone: yes
      become_user: root

    ##Angular-app install dependancy
    - name: Install angular dependancy
      command: sudo npm install
      args:
        chdir: ./code/angular-app/
      become_user: root

    ##Angular-app build
    - name: Build angular application
      command: sudo ng build
      args:
        chdir: ./code/angular-app/
      become_user: root

    ##Docker compose
    - name: run docker-compose
      command: docker-compose up -d --build
      args:
        chdir: ./code/compose/
      become_user: root
