#
# Copyright (C) 2019-2020 Heaptrace Technology
#
-
  name: User access Management
  hosts: localhost
  vars:
    - USER_DEV: "dev123"
    - PUBLIC_KEY_DEV: 'public_keys/dev.pub'
    - USER_ADMIN: "admin123"
    - PUBLIC_KEY_ADMIN: 'public_keys/admin.pub'
  tasks:
    ##Add dev user with limited
    - name: Add the user 'dev'
      user:
        name: '{{USER_DEV}}'
        append: yes

    - name: Set authorized key for user from file
      authorized_key:
        user: '{{USER_DEV}}'
        state: present
        key: "{{ lookup('file', '{{PUBLIC_KEY_DEV}}') }}"

    ##Add admin user with all privillage
    - name: Add the user 'dev'
      user:
        name: '{{USER_ADMIN}}'
        append: yes

    - name: Set authorized key for user from file
      authorized_key:
        user: '{{USER_ADMIN}}'
        state: present
        key: "{{ lookup('file', '{{PUBLIC_KEY_ADMIN}}') }}"

    - name: set root privillages
      lineinfile:
        path: /etc/sudoers
        line: '{{USER_ADMIN}} ALL=(ALL)NOPASSWD:ALL'
        insertbefore: EOF
      become_user: root
